# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Richa Namballa
title_separator: "|"
email: richa.namballa@nyu.edu
description: Professional Website
github_username: richa-namballa
minimal_mistakes_skin: contrast
search: true

repository: richa-namballa/richa-namballa.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone: America/New_York  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Richa Namballa"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD Student"
  location : "New York, NY, USA"
  links:
    - label: "Website"
      icon: "fa-solid fa-globe"
      url: "https://richa-namballa.github.io"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:richa.namballa@nyu.edu"
    - label: "Google Scholar"
      icon: fa-solid fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=S3W3Ql0AAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/richanamballa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/richa-namballa"
    - label: "University Profile"
      icon: "fa-solid fa-building-columns"
      url: "https://steinhardt.nyu.edu/people/richa-namballa"

collections:
  papers:
    output: false
  abstracts:
    output: false
  patents:
    output: false
  talks:
    output: false

footer:
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:richa.namballa@nyu.edu"
    - label: "Google Scholar"
      icon: fa-solid fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=S3W3Ql0AAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/richanamballa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/richa-namballa"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

lunr:
  search_within_pages: true
